config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create, :edit, :update]
  end
  delete '/doses/:id', to: 'doses#destroy', as: 'dose'
  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy]

  def index
    @cocktails = Cocktail.all
    query = params["cocktail-search"]
      if query && query != ""
        @cocktails = Cocktail.where("lower(name) LIKE '%#{query.downcase}%'")
      end
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.ingredient = Ingredient.find(params[:dose][:ingredient])
    unless params[:dose][:ingredient].blank?
      if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
    end
  end

  def update
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    if @dose.update(dose_params)
      redirect_to cocktail_path(@cocktail), notice: 'Item was updated.'
    else
      render :edit
    end
  end

  def edit
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description)
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_card.html.erb
<div class="col-xs-12 col-sm-4">
      <%= link_to cocktail_path(cocktail), class: "card-link" do %>
      <div class="card-container">
      <% if cocktail.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
      url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>');">
        <h2> <%= cocktail.name  %> </h2>
      </div>
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
      url('');">
        <h2> <%= cocktail.name  %> </h2>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1578404249298-291ee2775e55?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80);">
  <div class="banner-container">
    <h1>Cocktail Recipies</h1>
    <p>Find your favorites and some classics.</p>
  </div>
</div>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <%= render "card", cocktail:cocktail %>
      <% end %>
</div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add new cocktail</h1>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Submit", class: "btn btn-outline-primary" %>
        <% end %>
        <div class="path">
          <%= link_to "Go back", cocktails_path, class: "btn btn-outline-warning btn-sm" %>
        </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @cocktail.photo.key, height: 600, width: 800, crop: :fill %>');">
  <div class="banner-container">
    <h1> <%= @cocktail.name %> </h1>
  </div>
</div>
<div class="container py-4 cocktail-page">
  <div class="row">
  <div class="cocktail-box col-md-7">
    <h3>Description:</h3>
    <p><%= @cocktail.description %></p>


  </div>

  <div class="cocktail-box col-md-5">
    <div>
      <% if @cocktail.doses.empty? %>
      <p>
        No ingredients yet. Add yours!
      </p>
      <% else %>
      <h3> Ingredients </h3>
      <% end %>
    </div>


      <% @cocktail.doses.each do |dose| %>
      <div class="d-flex">
      <p><i class="fas fa-glass-whiskey"></i></i> <strong> <%= dose.ingredient.name %> - </strong><%= dose.description %>
        (<%= link_to "Edit", edit_cocktail_dose_path(@cocktail, dose) %>)
        (<%= link_to "Remove", dose_path(dose), method: :delete  %>)
        </p>
      </div>
      <% end %>

    <div>
      <%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-outline-primary", id: "ingredient-add-button"%>
      <%= link_to "Go back", cocktails_path, class: "btn btn-outline-warning" %>
      <%= link_to 'Delete Cocktail', @cocktail, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-xs" %>
    </div>
  </div>
</div>

</div>

app/views/doses/edit.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1568861280543-0961ffecdbb8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80);">
    <div class="banner-container">
      <h1>Add An Ingredient</h1>
    </div>
  </div>
  <section id="cover" class="min-vh-100">
    <div id="cover-caption">
      <div class="container">
        <div class="row text-black">
          <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
            <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.input :ingredient, collection: Ingredient.order(:name), selected: :ingredient, prompt: "Pick one from list" %>
            <%= f.input :description, :label => "Amount" %>
            <%= f.submit "Submit", class: "btn btn-outline-primary" %>
            <%= link_to "Go back", cocktails_path, class: "btn btn-outline-warning btn-sm" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/doses/new.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1568861280543-0961ffecdbb8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80);">
    <div class="banner-container">
      <h1>Add An Ingredient</h1>
    </div>
  </div>
  <section id="cover" class="min-vh-100">
    <div id="cover-caption">
      <div class="container">
        <div class="row text-black">
          <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
            <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.input :ingredient, collection: Ingredient.order(:name), prompt: "Pick one from list" %>
            <%= f.input :description, :label => "Amount" %>
            <%= f.submit "Submit", class: "btn btn-outline-primary" %>
            <%= link_to "Go back", cocktails_path, class: "btn btn-outline-warning btn-sm" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path, class: "link-icon" do %>
    <i class="fas fa-cocktail"></i><span class="title-bar">Mister Cocktail</span>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0" action="/cocktails">
      <input name="cocktail-search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div class="add-cocktail">
      <%= link_to "Add your cocktail", new_cocktail_path, class: "btn btn-outline-secondary" %>
    </div>
  </li>
</ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>